version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: sopassist-database
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sopassist
    ports:
      - '5435:5432'
    volumes:
      - sopassist_pgdata:/var/lib/postgresql/data

volumes:
  sopassist_pgdata:
